#---------------ClientCredentials----------------

url1=http://localhost:9091/oauth2/token
client_id1=dfd50f73-7135-476e-b718-e8456bb6205f
client_secret1=c0e64b8c-eeaf-4d44-a19a-07fb747dc5ad
grant_type1=client_credentials
scope1=openid

serviceC.account.verify.url=http://localhost:9091/api/v1/active/account/verify